version: 2

project_name: shelly-openmetrics-exporter

before:
  hooks:
    - go mod tidy
builds:
  - binary: shelly-openmetrics-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - riscv64
    goarm:
      - '6'
      - '7'

gomod:
  proxy: true

sboms:
  - artifacts: archive

dockers_v2:
  - id: multiarch
    images:
      - "ghcr.io/cimnine/shelly-openmetrics-exporter"
    tags:
      - "{{ .Tag }}"
      - "latest"
    labels: &docker_labels
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    flags:
      - "--pull=true"
  - id: amd64
    images:
      - "ghcr.io/cimnine/shelly-openmetrics-exporter"
    tags:
      - "amd64-{{ .Tag }}"
      - "amd64-latest"
    labels: *docker_labels
    platforms:
      - linux/amd64
    flags:
      - "--pull=true"
  - id: arm64
    images:
      - "ghcr.io/cimnine/shelly-openmetrics-exporter"
    tags:
      - "arm64-{{ .Tag }}"
      - "arm64-latest"
    labels: *docker_labels
    platforms:
      - linux/arm64
    flags:
      - "--pull=true"
  - id: armv6
    images:
      - "ghcr.io/cimnine/shelly-openmetrics-exporter"
    tags:
      - "armv6-{{ .Tag }}"
      - "armv6-latest"
    labels: *docker_labels
    platforms:
      - linux/arm/v6
    flags:
      - "--pull=true"
  - id: armv7
    images:
      - "ghcr.io/cimnine/shelly-openmetrics-exporter"
    tags:
      - "armv7-{{ .Tag }}"
      - "armv7-latest"
    labels: *docker_labels
    platforms:
      - linux/arm/v7
    flags:
      - "--pull=true"
  - id: riscv64
    images:
      - "ghcr.io/cimnine/shelly-openmetrics-exporter"
    tags:
      - "riscv64-{{ .Tag }}"
      - "riscv64-latest"
    labels: *docker_labels
    platforms:
      - linux/riscv64
    flags:
      - "--pull=true"

archives:
  - formats:
    - tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats:
        - zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    args:
      - sign-blob
      - '--oidc-provider=github-actions'
      - '--bundle=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: all
    output: false

docker_signs:
  - cmd: cosign
    args:
      - sign
      - '--oidc-provider=github-actions'
      - "${artifact}@${digest}"
      - '--yes'
    output: false

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
